### ISSUE TITLE
TypeError: console.log is not a function MMM-NiceThings.js:66:5 

### ISSUE THREAD

**Issue by flo269** [cowboysdude/MMM-NiceThings#2]
Hi,

I've been using this plugin for over year and it worked great. I now switced to current MM master and now get the following console output (and the NiceThings do obviously not appear on the screen):

Any hint on what I could do?
Thanks!
Cheers
Flo

Load script: modules/MMM-NiceThings//MMM-NiceThings.js loader.js:182:4
Module registered: MMM-NiceThings module.js:477:2
Bootstrapping module: MMM-NiceThings loader.js:152:3
Scripts loaded for: MMM-NiceThings loader.js:157:4
Load stylesheet: modules/MMM-NiceThings/MMM-NiceThings.css loader.js:197:4
Styles loaded for: MMM-NiceThings loader.js:159:5
Translations loaded for: MMM-NiceThings loader.js:161:6
Starting module: MMM-NiceThings MMM-NiceThings.js:26:9
MMM-NiceThings received a system notification: ALL_MODULES_STARTED module.js:156:4
MMM-NiceThings received a system notification: MODULE_DOM_CREATED module.js:156:4
MMM-NiceThings received a module notification: CALENDAR_EVENTS from sender: calendar module.js:154:4
MMM-NiceThings received a module notification: CURRENTWEATHER_DATA from sender: currentweather module.js:154:4
**TypeError: console.log is not a function**[Learn More] MMM-NiceThings.js:66:5

processNice http://10.10.10.13:8080/modules/MMM-NiceThings//MMM-NiceThings.js:66
socketNotificationReceived http://10.10.10.13:8080/modules/MMM-NiceThings//MMM-NiceThings.js:83
socket http://10.10.10.13:8080/js/module.js:246
 MMSocket http://10.10.10.13:8080/js/socketclient.js:25
 emit http://10.10.10.13:8080/socket.io/socket.io.js:6
 onevent http://10.10.10.13:8080/socket.io/socket.io.js:7 
onevent http://10.10.10.13:8080/js/socketclient.js:19 
onpacket http://10.10.10.13:8080/socket.io/socket.io.js:7 
exports http://10.10.10.13:8080/socket.io/socket.io.js:7
 emit http://10.10.10.13:8080/socket.io/socket.io.js:6 
ondecoded http://10.10.10.13:8080/socket.io/socket.io.js:6 
exports http://10.10.10.13:8080/socket.io/socket.io.js:7 
emit http://10.10.10.13:8080/socket.io/socket.io.js:6 
add http://10.10.10.13:8080/socket.io/socket.io.js:6 
ondata http://10.10.10.13:8080/socket.io/socket.io.js:6 
exports http://10.10.10.13:8080/socket.io/socket.io.js:7 
emit http://10.10.10.13:8080/socket.io/socket.io.js:6 
onPacket http://10.10.10.13:8080/socket.io/socket.io.js:6 
setTransport http://10.10.10.13:8080/socket.io/socket.io.js:6 
emit http://10.10.10.13:8080/socket.io/socket.io.js:6 
onPacket http://10.10.10.13:8080/socket.io/socket.io.js:7 
onData http://10.10.10.13:8080/socket.io/socket.io.js:7 
onmessage http://10.10.10.13:8080/socket.io/socket.io.js:7

**Comment by cowboysdude** [comment]
Took it out :)  Thank you!
